### ISSUE TITLE
can support API2D?

### ISSUE THREAD

**Issue by itsdrchen** [webpilot-ai/Webpilot#30]
Please support third-party API services such as API2D, Thanks!

**Comment by kaiyo655** [comment]
Azure Openai API support needed also

**Comment by CocoSgt** [comment]
> 

Custom hosts will be supported in the next version, which has already been developed. The new version is currently being debugged, and it will take about 1-2 weeks to be launched.

**Comment by webmasterfsd** [comment]
Hello there,

I'm really enjoying this extension, but I've noticed that the prompts aren't appearing when I use the shortcode or click the extension button in Chrome. They only seem to show up when I select some text.

Would you happen to know how I can resolve this issue? Or perhaps let me know when the new version with this feature will be released?

Screenshot attached.

Thank you for your help!

![Uploading Screenshot_145.png…]()

**Comment by CocoSgt** [comment]
Supported. Go to settings and check the "self host" option.
