### ISSUE TITLE
The web page always only report  "Context invalidated, press to refresh"

### ISSUE THREAD

**Issue by davidzhr** [webpilot-ai/Webpilot#46]
Hi experts,

could you help take  a look the below issue?

![image](https://github.com/webpilot-ai/Webpilot/assets/12372641/12aac2dd-5cbc-4623-8316-950979fb30ea)

**Comment by CocoSgt** [comment]
F5 / Refresh

**Comment by davidzhr** [comment]
@CocoSgt 

sure， F5 will refresh the page. if i had enter some import content in the page,  this picture hide my submit button.  if i press the F5, the content will lost.

do you know which module control this tooltip?
