### ISSUE TITLE
Azure Openai API support needed also

### ISSUE THREAD

**Issue by blakefan** [webpilot-ai/Webpilot#51]
Azure Openai API support needed also

**Comment by shikelong** [comment]
+1

**Comment by CocoSgt** [comment]
Already supported. Go to [settings](chrome-extension://biaggnjibplcfekllonekbonhfgchopo/options.html) and check the "self host" option.

**Comment by shikelong** [comment]
<img width="623" alt="image" src="https://github.com/webpilot-ai/Webpilot/assets/4499997/eaab4dc2-8d1b-49f1-92ae-7a4e0464c85b">

not works. no input to allow us to type azure openai api-key and deployment name. @CocoSgt 😅

**Comment by buqiuwenda** [comment]
+1
