### ISSUE TITLE
Support the `ecs` key to close the webpilot

### ISSUE THREAD

**Issue by SimFG** [webpilot-ai/Webpilot#53]

**Comment by banbri** [comment]
The plugin already supports the "ESC" key to close the Webpilot dialog box, just press "ESC" twice.

**Comment by SimFG** [comment]
It doesn't seem to take effect. If I click outside the dialog, I can exit by clicking `ecs`, but it seems inconvenient

**Comment by CocoSgt** [comment]
This feature exists, but due to a bug not being triggered, the fix will be provided in the next version.
