### ISSUE TITLE
Uncaught (in promise)  error at Chrome v93.x

### ISSUE THREAD

**Issue by eagle518** [webpilot-ai/Webpilot#54]
options.html:1 Uncaught (in promise) {}[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
Promise.then (async)
setup @ options.2a742e8f.js:1
p @ options.2a742e8f.js:1
(anonymous) @ options.2a742e8f.js:1
rF @ options.2a742e8f.js:1
W @ options.2a742e8f.js:1
Y @ options.2a742e8f.js:1
B @ options.2a742e8f.js:1
ec @ options.2a742e8f.js:1
mount @ options.2a742e8f.js:1
t.mount @ options.2a742e8f.js:1
(anonymous) @ options.2a742e8f.js:1

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
