### ISSUE TITLE
Does webpilot support Azure OpenAPI key?

### ISSUE THREAD

**Issue by jeejeekwan** [webpilot-ai/Webpilot#57]

**Comment by jasonalang** [comment]
I have the same question, look forward to an answer from the dev team.

**Comment by CocoSgt** [comment]
Comming Soon!

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025

**Comment by jwalli** [comment]
Is there a guide on how to connect Azure OpenAI? I have created an Azure OpenAI resource, but the data I provide in the web pilot does not seem to be correct? Can someone help and say where to get the 4 required data?

API_KEY
API_HOST
API_VERSION
DEPLOYMENT_ID

Thanks for the support.

**Comment by buqiuwenda** [comment]
+1
