### ISSUE TITLE
Unverified plugin

### ISSUE THREAD

**Issue by fruini** [webpilot-ai/Webpilot#58]
The plugin suddenly became unverified and has been taken off the plugin store, as shown in screenshots attached.
![Screenshot_20230713_153713_Kiwi Browser](https://github.com/webpilot-ai/Webpilot/assets/85406813/b908bba7-e230-417b-acfc-9b991f38ba73)
![Screenshot_20230713_153824_Kiwi Browser](https://github.com/webpilot-ai/Webpilot/assets/85406813/57320947-0ea9-4ffd-9c34-2e0e8a1b4dd3)

**Comment by jmorley88** [comment]
Also not working for me - any updates

**Comment by thatonehen** [comment]
Okay, thank you.

**Comment by zh0775** [comment]
As of now, WebPilot is still not searchable.

**Comment by CocoSgt** [comment]
> As of now, WebPilot is still not searchable.

Yes, it's strange. I have already provided feedback to the responsible person at OpenAI
