### ISSUE TITLE
Timeout on API

### ISSUE THREAD

**Issue by zanderman22** [webpilot-ai/Webpilot#63]
Hi Team,

I'm getting time-outs for prompts via the API which work fine on OpenAI's UI with Webpilot as a plugin. Here is an example:

{
    "content": "Please research innovations in charity fundraising for me. I want summaries of 3 successful fundraising campaigns used by charities in the last 3 years. Please provide the name of the charity, a summary of their campaign, and links to your source."
}

Via the API, it times out (5+ attempts and no problems with other smaller prompts). On OpenAI I get an exemplary response from Webpilot's plugin. 

Any ideas why?

Cheers,

Dorian

**Comment by CocoSgt** [comment]
Which API? The Chrome Extension or Watt?

**Comment by zanderman22** [comment]
Sorry, yeah, Watt.

**Comment by CocoSgt** [comment]
please report to: contact@webpilot.ai
