### ISSUE TITLE
输入框颜色很淡

### ISSUE THREAD

**Issue by Gy-Hu-Star** [webpilot-ai/Webpilot#65]
输入
<img width="494" alt="image" src="https://github.com/webpilot-ai/Webpilot/assets/120406793/a27022e0-e0f4-49f8-98cd-19bbc43d6ae7">

全选
<img width="477" alt="image" src="https://github.com/webpilot-ai/Webpilot/assets/120406793/b5ce39d9-12aa-45a0-ad1c-4842c1e2f16a">

请问如何解决？谢谢！

**Comment by CocoSgt** [comment]
Style isolation has not been implemented yet, it will be addressed in the next version

**Comment by Zzzccs123** [comment]
Is it necessary to first fix the issue by adding a fixed color style value?

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
