### ISSUE TITLE
Optimize the interaction of input boxes

### ISSUE THREAD

**Issue by Zzzccs123** [webpilot-ai/Webpilot#67]
After entering content in the webpilot input box and performing a search, when I close webpilot and reopen it, the old input box content remains, but the response content is lost. I expect one of the following two interactions:
1. When reopened, the input box content and the corresponding response content are retained.
2. When reopened, all content is cleared.
I lean towards the second option because when I close webpilot, it means I no longer need the current content. Therefore, when I reopen it, I would prefer to see a reset input box.

Please evaluate whether there is a need to optimize this interaction. If this interaction needs to be optimized, I'm more than happy to do it.

Thank you!

**Comment by CocoSgt** [comment]
Thank you for bringing up this excellent point. Here is how we are considering it: 

In most cases, users tend to use the same prompt on the ask page, so the next time it is opened, the previous prompt will be automatically retained (and selected). However, there are still some issues with the current interaction, and we plan to address them in the next major update. We welcome your contribution to the code when the time comes.

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
