### ISSUE TITLE
[Feature request] Can we consider supporting the resize of the output box?

### ISSUE THREAD

**Issue by aiyogg** [webpilot-ai/Webpilot#68]
Thank you very much to the developers for creating this excellent tool. During my usage, I found that the message box generated by AI cannot be resized. I'm wondering if there are any plans to support resizing of the output box?

**Comment by CocoSgt** [comment]
Will be supported in next update

**Comment by TianmiFang** [comment]
Hello Aiyogg!

Thanks for your feedback. We are working on a new version enabling resizing and other features. We will keep you updated.

Thanks,
Webpilot Design Team

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
