### ISSUE TITLE
使用自己的 key 提示：Incorrect API Key. Please check with the provider

### ISSUE THREAD

**Issue by Chorer** [webpilot-ai/Webpilot#69]
在 https://platform.openai.com/account/api-keys 获取 openai key，输入后有下面的报错：
![image](https://github.com/webpilot-ai/Webpilot/assets/43442630/82b136dd-feea-47b9-8a7d-33d5a1632c6e)
请问是因为我当前使用的不是 paid plan，并且已经用完了免费额度吗？
![image](https://github.com/webpilot-ai/Webpilot/assets/43442630/2fe4eeb3-124b-47f6-a997-d1dbe0805dc7)

**Comment by CocoSgt** [comment]
Yes, and your credit has expired on 04/01/2023

To resolve this, you have three options: set up a paid plan, use a third-party proxy, or try WebPilot's free credit (50 requests per week)
