### ISSUE TITLE
The extension make some web page text WHITE with the injecting css/有些网页文字被注入的样式变白

### ISSUE THREAD

**Issue by TownTowner** [webpilot-ai/Webpilot#73]
Like below/如下图：
![image](https://github.com/webpilot-ai/Webpilot/assets/10682896/e7016d87-9504-4154-825c-e34e448e7513)

The web page/网页地址: [https://blog.csdn.net/Javon_huang/article/details/122252177](url).

Disable this extension is OK/关掉这个扩展就没问题了.

**Comment by CocoSgt** [comment]
The style isolation has not been done in this version, so there may be some style issues in certain cases. It will be fixed in the next version

**Comment by 97z4moon** [comment]
> The style isolation has not been done in this version, so there may be some style issues in certain cases. It will be fixed in the next version

Consider using [MDN: shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM)
