### ISSUE TITLE
Override styles for web code samples.

### ISSUE THREAD

**Issue by long-woo** [webpilot-ai/Webpilot#74]
![image](https://github.com/webpilot-ai/Webpilot/assets/3394035/d3b304b3-2d66-4a19-bc48-e21643a2240a)

https://vant-ui.github.io/vant/#/zh-CN/list

When I close the Webpilot plugin in Edge browser, it is normal. When it is opened, it will display the problem in the image.

**Comment by CocoSgt** [comment]
The next version will fix it
