### ISSUE TITLE
Why such a withdrawn, timid UI? - Feedback

### ISSUE THREAD

**Issue by ofmarconi** [webpilot-ai/Webpilot#75]
![image](https://github.com/webpilot-ai/Webpilot/assets/6594795/53a4f8e6-1a99-4a10-9535-8a3f722bea9f)

See in the print how much screen I have available, your plugin is unique, but it could be improved just by increasing the response box, not to mention that you shouldn't push the text up if you get to the bottom since you didn't even have time to read the first line when he concludes.

:D

**Comment by CocoSgt** [comment]
The next version will make changes to this UI (the design draft is almost finished! :D)

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
