### ISSUE TITLE
Feature Request - XtremeLazymode

### ISSUE THREAD

**Issue by ofmarconi** [webpilot-ai/Webpilot#76]
Hello,

I would like to request a new button in the question box, he would be responsible for reading the page and already suggesting questions that I could ask for that page.

For example:

1. I visit the article https://www.washingtonpost.com/world/2023/09/04/putin-kim-meeting-weapons-deal-russia-north-korea/
2. I press the button and your extension asks GPT: What questions do you suggest I ask for this page?
3. The GPT answer must be in threads without explanations, only the suggested questions
4. Which should be interpreted as Shortcuts to the next question
5. Somehow it would be nice to keep the suggestions so that the user can continue to explore.

That it :D 

Thx so much!

**Comment by CocoSgt** [comment]
Already designed, currently in development

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
