### ISSUE TITLE
自定义CSS

### ISSUE THREAD

**Issue by lazydao** [webpilot-ai/Webpilot#78]
目前markdownWrap块显示空间太小了，如果能自定义height和width就太好了。

**Comment by CocoSgt** [comment]
The new version is now supported, developed and will be synchronized later

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
