### ISSUE TITLE
添加第三方API接口，无法直接使用，必须选中文本后使用

### ISSUE THREAD

**Issue by xulei-shl** [webpilot-ai/Webpilot#80]
配置的代理接口如下图
![image](https://github.com/webpilot-ai/Webpilot/assets/13896259/4aada35c-4b91-44ee-a039-e06db826b6b0)

在划词选中部分文本后调用，可以正常返回结果。但直接快捷键调出窗口，输入“总结网页内容”之类的问题就会报错
![image](https://github.com/webpilot-ai/Webpilot/assets/13896259/1d0d3b48-958a-43b2-9a90-a3ad54a60ca4)

![image](https://github.com/webpilot-ai/Webpilot/assets/13896259/2fc97808-5d0b-4cf0-8d87-68b6793e9e17)

**Comment by CocoSgt** [comment]
Check on：https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo/

V 0.9.1025
