### ISSUE TITLE
Hi @CocoSgt,

### ISSUE THREAD

**Issue by webmasterfsd** [webpilot-ai/Webpilot#87]
Hi @CocoSgt,

Thank you for the excellent update, which is working perfectly. However, I've encountered an issue with the extension not saving larger prompts or text in context.

I've noticed that when I create a new prompt with larger text, it appears to be created and saved successfully. However, upon refreshing the page or opening a new one, the extension loses or doesn't retain that particular prompt.

Could you please provide guidance on how to create bigger or larger text prompts, or how to increase the extension's memory to accommodate larger prompt data?

Thank you.

_Originally posted by @webmasterfsd in https://github.com/webpilot-ai/Webpilot/issues/35#issuecomment-1792940447_

**Comment by CocoSgt** [comment]
Regarding the issue you mentioned about the extension not saving larger prompts or text in context, I haven't experienced this problem myself. 

It would be helpful if you could provide a more specific example or steps to reproduce the issue.

**Comment by webmasterfsd** [comment]
Hi @CocoSgt,

Thank you for your prompt response.

To replicate the issue, kindly insert any longer prompt text.
Kindly proceed by copying and pasting the below text into the extension. Save the changes, refresh the page, and revisit the prompts list for verification.

Thank you.

**********Example:
Thank you for the excellent update, which is working perfectly. However, I've encountered an issue with the extension not saving larger prompts or text in context.

I've noticed that when I create a new prompt with larger text, it appears to be created and saved successfully. However, upon refreshing the page or opening a new one, the extension loses or doesn't retain that particular prompt.

Could you please provide guidance on how to create bigger or larger text prompts, or how to increase the extension's memory to accommodate larger prompt data?

Thank you for the excellent update, which is working perfectly. However, I've encountered an issue with the extension not saving larger prompts or text in context.

I've noticed that when I create a new prompt with larger text, it appears to be created and saved successfully. However, upon refreshing the page or opening a new one, the extension loses or doesn't retain that particular prompt.

Could you please provide guidance on how to create bigger or larger text prompts, or how to increase the extension's memory to accommodate larger prompt data?
********

**Comment by CocoSgt** [comment]
Fixed

**Comment by CocoSgt** [comment]
code would be approved in 1 day

**Comment by webmasterfsd** [comment]
Hi @CocoSgt 

Thanks. It's saving the longer prompts now, but the prompt context length is still short for me; how can I increase its context length to 1000 words or 6000 characters?

Thanks,

**Comment by webmasterfsd** [comment]
Hello @CocoSgt,

I hope you're doing well! I was wondering if there are any updates on the new version? I would greatly appreciate any information you can provide.

Thank you,

**Comment by webmasterfsd** [comment]
Hello @CocoSgt,

I hope you're doing well! I was wondering if there are any updates on the new version? I would greatly appreciate any information you can provide.

Thank you,

**Comment by CocoSgt** [comment]
ooooops.... I fixed this conbined with gpt-4v feature.....so it is still waiting for the non-preview gpt-4v api

**Comment by webmasterfsd** [comment]
Hi @CocoSgt 

Thank you for your prompt response. Currently, I am using the GPT-4 turbo preview version.

Could you please provide guidance on resolving this prompt issue? I am in great need of assistance.

Additionally, I am interested in accessing your updated gpt-4v plugin. It would be immensely helpful for me.

Thank you.

**Comment by CocoSgt** [comment]
I don't have my computer with me right now, but once the Christmas break is over, I'll send you a branch link / .zip file so you can access it before the non-preview API gets released

**Comment by webmasterfsd** [comment]
Thank you very much; your kindness is truly appreciated.

**Comment by webmasterfsd** [comment]
Just a quick friendly reminder, if you have access to your laptop, could you please send me the .zip file? Thank you in advance!

**Comment by CocoSgt** [comment]
will be in next week, I think

**Comment by CocoSgt** [comment]
and... could you leave an email address? I'll send it to u

**Comment by webmasterfsd** [comment]
Yes, please sent it to this email:  oyousuf936@gmail.com

Thank you so much!!

**Comment by webmasterfsd** [comment]
Could you please provide me with an update on this matter?

**Comment by CocoSgt** [comment]
I'll send it to you later next week, and Happy New Year!
