### ISSUE TITLE
why today webpilot answer by chinese have so much more problem?   anything happened?

### ISSUE THREAD

**Issue by melfebulu** [webpilot-ai/Webpilot#95]
The market is slowly coming to a realization that the existing RAG stack for building AI Chatbots is falling short of business expectations. There are many recommendations floating around, and on top of that, new ideas are popping up every day. [Advanced RAG](https://pub.towardsai.net/advanced-rag-techniques-an-illustrated-overview-04d193d8fec6), a significantly complex system with too many components and associated knobs to tune, is now the recommended solution. Adjusting the knobs in advanced RAG for any given use case requires a dedicated team of experts, making the solution non-repeatable

below is answer by webpilot's chatgpt:

场逐认识，现的用构建聊天器人 RAG 栈无满足务期。有多建在四流传而且天都出现的想。现推荐解决案是进的 AG，是一个常复的系统有太的组和相关旋钮调，适任何定的例都一个门的队来调，使该解方案可重。

lost so many chinese word, why?   before is ok

**Comment by melfebulu** [comment]
![webpilot_bug](https://github.com/webpilot-ai/Webpilot/assets/47744908/fcf8aaae-854a-4b3a-bff9-d11c5398d92c)

**Comment by CocoSgt** [comment]
According to the official statement, there is currently a UTF-8 encoding issue with OpenAI API, which will be fixed in an update this week

**Comment by melfebulu** [comment]
recovery now :)

**Comment by melfebulu** [comment]
bad.. no stable, problem again....

**Comment by CocoSgt** [comment]
still working on it and try to identify this

**Comment by pluto-the-lost** [comment]
I believe sometime even English answer has the same problem, although not as frequent as in Chinese. So it might not be only the utf-coding issues

**Comment by CocoSgt** [comment]
identified, fix, uploaded to Git and pendding review in chrome store
