### ISSUE TITLE
broken, missing and unstructured output 

### ISSUE THREAD

**Issue by webmasterfsd** [webpilot-ai/Webpilot#96]
Hi @CocoSgt

I need your urgent help. I've been using your extension every day.

Yesterday, I encountered an issue. The output I received is broken and unstructured (screenshot sent in email), even though I used the same prompt as before. Interestingly, when I tried a different extension, I received a normal response.

I just checked, and your extension is not available in Google Chrome anymore. Also, I see the same issue and broken output on every computer.

Now, I'm receiving broken responses or missing content on every prompt.

Please fix it.

Thank you so much.

**Comment by CocoSgt** [comment]
identified, that is issue of OpenAI API, last week, they said they will fix it this week

**Comment by CocoSgt** [comment]
And…. https://chrome.google.com/webstore/detail/webpilot-copilot-for-all/biaggnjibplcfekllonekbonhfgchopo

**Comment by webmasterfsd** [comment]
Thank you for the response. But I get normal results when using the same API on another Chrome extension. @CocoSgt

**Comment by webmasterfsd** [comment]
I also submitted a ticket there and now they're requesting additional details. Do you have a ticket ID I can reference in my response?

**Comment by CocoSgt** [comment]
<img width="658" alt="image" src="https://github.com/webpilot-ai/Webpilot/assets/6043666/5cc2ce02-61e3-4387-9dcf-47f8f53d48d8">
it should be solved

**Comment by webmasterfsd** [comment]
![Screenshot_152](https://github.com/webpilot-ai/Webpilot/assets/85025970/66352938-a233-4af1-9fcf-4d8498f6002d)
I made another attempt, but unfortunately, the problem persists.

**Comment by webmasterfsd** [comment]
Another screenshot 
![Screenshot_153](https://github.com/webpilot-ai/Webpilot/assets/85025970/fde10101-ae26-4311-a81d-c0e3e76af08a)
broken and missing content output.

**Comment by CocoSgt** [comment]
sooooo weird, and I will try to look into it

**Comment by webmasterfsd** [comment]
Please keep me updated on any progress. I'll keep trying as well. My entire team relies on this helpful tool, so it's important to get this issue fixed.

Thank you so much for your cooperation! I really appreciate it.

**Comment by CocoSgt** [comment]
identified, fix, uploaded to Git and pendding review in chrome store

**Comment by webmasterfsd** [comment]
Thanks a lot! I really appreciate it.

Would you mind emailing me the Dev Version? I'll give it a check and let you know if I find any issues.

I have just sent you an email with the subject line "broken, missing and unstructured output #96"

Thanks,

**Comment by webmasterfsd** [comment]
Thanks a lot! I really appreciate it.

Would you mind emailing me the Dev Version? I'll give it a check and let you know if I find any issues.

I have just sent you an email with the subject line. "broken, missing and unstructured output #96"

Thanks,
